package model

// BaseModel is the shared primary-key carrier for tables whose identifiers are
// generated by the application (common/idgen snowflake) instead of a database
// sequence.
//
// Embed it anonymously so GORM flattens ID into the parent table as the
// primary key. Assign the identifier after constructing the value, never in
// the struct literal, because GORM treats a zero primary key as "not set" and
// would fall back to the driver default:
//
//	key := ByokKey{UserId: userId, Provider: provider}
//	key.ID = idgen.Next()
//
// ID is tagged `json:",string"` because snowflake values exceed 2^53 and a
// JavaScript client would otherwise round them.
type BaseModel struct {
	ID int64 `json:"id,string" gorm:"primaryKey;autoIncrement:false"`
}
