// Package idgen issues application-generated snowflake identifiers.
//
// TokenSplice tables that must stay shardable across independently provisioned
// databases use these IDs instead of a database sequence, so a row keeps the
// same primary key when it is copied, exported, or replayed between nodes.
//
// Layout (64 bits, big-endian value, always positive):
//
//	| 1 bit unused | 41 bits unix milliseconds since Epoch | 10 bits node | 12 bits sequence |
//
// 41 bits of milliseconds cover roughly 69 years past Epoch; 12 bits of
// sequence allow 4096 IDs per node per millisecond.
//
// IDs can exceed 2^53, which JavaScript cannot represent exactly, so every
// API response must serialize them as strings (see types.FlexInt64 and the
// `json:",string"` tag on model.BaseModel).
package idgen

import (
	"hash/fnv"
	"os"
	"strconv"
	"sync"
	"time"
)

// Epoch is the offset applied to wall-clock milliseconds. 2025-01-01T00:00:00Z.
const Epoch int64 = 1735689600000

const (
	nodeBits     = 10
	sequenceBits = 12

	nodeShift      = sequenceBits
	timestampShift = nodeBits + sequenceBits

	// MaxNode is the largest assignable node id (10 bits).
	MaxNode = 1<<nodeBits - 1
	// MaxSequence is the largest per-millisecond sequence value (12 bits).
	MaxSequence = 1<<sequenceBits - 1

	// nodeEnvVar lets an operator pin a node id explicitly, which is required
	// whenever more than one gateway process shares a database.
	nodeEnvVar = "SNOWFLAKE_NODE_ID"
)

var (
	mu       sync.Mutex
	node     = deriveNode()
	lastTime int64
	sequence int64
)

// deriveNode resolves the process node id. An explicit SNOWFLAKE_NODE_ID wins;
// otherwise the hostname and pid are hashed so co-located processes still
// differ without any configuration.
func deriveNode() int64 {
	if raw := os.Getenv(nodeEnvVar); raw != "" {
		if parsed, err := strconv.Atoi(raw); err == nil && parsed >= 0 && parsed <= MaxNode {
			return int64(parsed)
		}
	}
	hostname, err := os.Hostname()
	if err != nil {
		hostname = "unknown"
	}
	hash := fnv.New64a()
	hash.Write([]byte(hostname))
	hash.Write([]byte(strconv.Itoa(os.Getpid())))
	hash.Write([]byte(strconv.FormatInt(time.Now().UnixNano(), 10)))
	return int64(hash.Sum64() % uint64(MaxNode+1))
}

// Node returns the node id embedded in identifiers generated by this process.
func Node() int64 {
	mu.Lock()
	defer mu.Unlock()
	return node
}

// Next returns the next unique identifier. It blocks while the sequence for
// the current millisecond is exhausted, and it stays on the last observed
// timestamp if the wall clock moves backwards so IDs remain unique and
// monotonically increasing instead of colliding with already issued ones.
func Next() int64 {
	mu.Lock()
	defer mu.Unlock()

	now := time.Now().UnixMilli() - Epoch
	if now < lastTime {
		now = lastTime
	}
	if now == lastTime {
		sequence = (sequence + 1) & MaxSequence
		if sequence == 0 {
			for now <= lastTime {
				now = time.Now().UnixMilli() - Epoch
			}
		}
	} else {
		sequence = 0
	}
	lastTime = now

	return now<<timestampShift | node<<nodeShift | sequence
}

// Parse splits an identifier back into its components for diagnostics.
func Parse(id int64) (timestamp time.Time, nodeID int64, seq int64) {
	seq = id & MaxSequence
	nodeID = (id >> nodeShift) & MaxNode
	timestamp = time.UnixMilli((id >> timestampShift) + Epoch)
	return timestamp, nodeID, seq
}
